<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKuk7Gx4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKuk7Gx4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKuk7Gx4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKuk7Gx4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKuk7Gx4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kuk7Gx4',
    'container.build_id' => '0c70e11f',
    'container.build_time' => 1707322056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKuk7Gx4');
