vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        sinister_vehicle_images:
            uri_prefix: /images/sinister_vehicles
            upload_destination: '%kernel.project_dir%/public/images/sinister_vehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer