#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\AdminController::admin

client:
    path: /client
    controller: App\Controller\ClientController::client

HomePage:
    path: /HomePage
    controller: App\Controller\ClientController::HomePage

showSinisterLifeAdmin:
    path: /showSinisterLifeAdmin
    controller: App\Controller\AdminController::showSinisterLifeAdmin

showMedicalSheetsAdmin:
    path: /showMedicalSheetsAdmin
    controller: App\Controller\AdminController::showMedicalSheetsAdmin

showPrescriptionsAdmin:
    path: /showPrescriptionsAdmin
    controller: App\Controller\AdminController::showPrescriptionsAdmin
