#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\AdminController::admin

client:
    path: /client
    controller: App\Controller\ClientController::client

HomePage:
    path: /HomePage
    controller: App\Controller\ClientController::HomePage

New_VehicleRequest:
    path: /new_VehicleRequest
    controller: App\Controller\VehicleRequestController::new

New_PropretyRequest:
    path: /New_PropretyRequest
    controller: App\Controller\PropretyRequestController::new


New_LifeRequest:
    path: /New_LifeRequest
    controller: App\Controller\LifeRequestController::new

New_ContratHabitat:
    path: /New_ContratHabitat
    controller: App\Controller\ContratHabitatController::new

New_ContratVehicule:
    path: /New_ContratVehicule
    controller: App\Controller\ContratVehiculeController::new

New_ContratVie:
    path: /New_ContratVie
    controller: App\Controller\ContratVieController::new


app_contrat_habitat_show_in_contrat:
    path: '/showDemandes_habitat'
    controller: 'App\Controller\ContratHabitatController::showDemandes_habitat'
    methods: ['GET']

app_contrat_vie_show_in_contrat:
    path: '/showDemandes_vie'
    controller: 'App\Controller\ContratVieController::showDemandes_vie'
    methods: ['GET']

app_contrat_vehicule_show_in_contrat:
    path: '/showDemandes_vehicule'
    controller: 'App\Controller\ContratVehiculeController::showDemandes_vehicule'
    methods: ['GET']

