#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\AdminController::admin

client:
    path: /client
    controller: App\Controller\ClientController::client
