#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\AdminController::admin

client:
    path: /client
    controller: App\Controller\ClientController::client

HomePage:
    path: /HomePage
    controller: App\Controller\ClientController::HomePage
sinistres_by_user:
    path: /usersinistre/{userId}
    controller: App\Controller\SinisterPropertyController::sinistresByUser

