#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\AdminController::admin

client:
    path: /client
    controller: App\Controller\ClientController::client
register:
    path: /register
    controller: App\Controller\RegistrationController::register
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
users-profile:
    path: /users-profile
    controller: App\Controller\ProfileController::usersProfile
editprofile:
    path: /editprofile
    controller: App\Controller\ProfileController::editprofile
# config/routes.yaml

changePassword:
    path: /changePassword
    controller: 'App\Controller\ProfileController::changePassword'
    methods: ['GET', 'POST']
forgot_password:
    path: /forgetPassword
    controller: 'App\Controller\ProfileController::changePassword'
    methods: ['GET', 'POST']

profile:
    path: /profile
    controller: 'App\Controller\ProfileController::profile'
    methods: ['GET']
admin_profile:
    path: /adminprofile
    controller: 'App\Controller\ProfileController::adminprofile'
    methods: ['GET']

# app_user_delete:
#     path: /delete
#     controller: App\Controller\UserController::delete
# app_user_new:
#     path: /new
#     controller: App\Controller\UserController::new
# getAllusers:
#     path: /getAllusers
#     controller: App\Controller\UserController::getAllusers
admincreateuser:
    path: /admincreateuser
    controller: App\Controller\UserController::adminCreateUser
sendSms:
    path: /sendSms
    controller: App\Controller\UserController::sendSms
    methods: ['GET', 'POST']
# config/routes.yaml

two_factor_authentication:
    path: /two-factor-authentication
    controller: App\Controller\TwoFactorAuthentificationController::index
    methods: ['GET', 'POST']
